package cli

import (
	"fmt"
	"go/format"
	"io"
	"os"
	"path"
	"reflect"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/burgrp/bleriot/lib/shared/inventory"
)

// firmwareNodePkg is the import path of the firmware-side node package that
// declares node.Provisioning. The generated main() references it as "node".
const firmwareNodePkg = "github.com/burgrp/bleriot/lib/node"

// newGenCmd builds the "gen" subcommand: emit the firmware provisioning source
// for one inventory instance to stdout. It touches no hardware; the Makefile
// redirects its output into a generated, gitignored Go file that the firmware
// build compiles in, baking the device's identity and config into the image.
//
// The instance is chosen by name, or defaulted to the sole instance when the
// inventory has exactly one.
func newGenCmd(inv inventory.Inventory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gen [name]",
		Short: "Generate the firmware provisioning source for a device",
		Long: "Emit a Go source file (to stdout) that bakes the named inventory " +
			"instance's identity (RF address, key, channel, spread factor) and config " +
			"into the firmware image. The Makefile redirects this into a generated file " +
			"the firmware build compiles in. With no name, the sole instance is used.",
		Args: cobra.MaximumNArgs(1),
	}
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		var name string
		if len(args) == 1 {
			name = args[0]
		}
		return runGen(inv, name, os.Stdout)
	}
	return cmd
}

func runGen(inv inventory.Inventory, name string, w io.Writer) error {
	if err := inv.Validate(); err != nil {
		return fmt.Errorf("inventory: %w", err)
	}
	inst, err := resolveInstance(inv, name)
	if err != nil {
		return err
	}
	src, err := renderProvisioning(inst)
	if err != nil {
		return fmt.Errorf("instance %q: %w", inst.Name, err)
	}
	_, err = io.WriteString(w, src)
	return err
}

// resolveInstance picks the instance to generate for: the one named, or the sole
// instance when name is empty. It errors on an unknown name, an empty inventory,
// or an ambiguous default.
func resolveInstance(inv inventory.Inventory, name string) (inventory.Instance, error) {
	if name != "" {
		for _, inst := range inv {
			if inst.Name == name {
				return inst, nil
			}
		}
		return inventory.Instance{}, fmt.Errorf("no inventory instance named %q; known: %s", name, instanceNames(inv))
	}
	switch len(inv) {
	case 1:
		return inv[0], nil
	case 0:
		return inventory.Instance{}, fmt.Errorf("inventory is empty; nothing to generate")
	default:
		return inventory.Instance{}, fmt.Errorf("inventory has %d instances; name one: %s", len(inv), instanceNames(inv))
	}
}

// instanceNames lists the inventory's instance names, sorted, for error messages.
func instanceNames(inv inventory.Inventory) string {
	names := make([]string, 0, len(inv))
	for _, inst := range inv {
		names = append(names, inst.Name)
	}
	sort.Strings(names)
	return strings.Join(names, ", ")
}

// renderProvisioning builds the gofmt'd source of the firmware's generated
// main(): it constructs a node.Provisioning from the instance's baked identity
// and calls bleriotMain with it and the instance's config. The result is
// formatted (and thereby parse-checked) before being returned.
func renderProvisioning(inst inventory.Instance) (string, error) {
	prov := fmt.Sprintf(`node.Provisioning{
	Address:      %s,
	Key:          %s,
	Channel:      %d,
	SpreadFactor: %d,
}`, byteArrayLiteral(inst.Address[:]), byteArrayLiteral(inst.Key[:]), inst.Channel.Number, uint8(inst.Channel.SpreadFactor))

	// The generated main() always needs the firmware node package for
	// Provisioning; the config literal may pull in the package(s) that declare its
	// types.
	imports := map[string]string{firmwareNodePkg: "node"}

	var call string
	if inst.Config == nil {
		call = fmt.Sprintf("bleriotMain(%s)", prov)
	} else {
		cfgLit := fmt.Sprintf("%#v", inst.Config)
		for p, name := range configImports(inst.Config, cfgLit) {
			imports[p] = name
		}
		call = fmt.Sprintf("bleriotMain(%s, %s)", prov, cfgLit)
	}

	var b strings.Builder
	b.WriteString("//go:build tinygo\n\n")
	b.WriteString(`// Code generated by "bleriot gen"; DO NOT EDIT.` + "\n\n")
	b.WriteString("package main\n\n")
	b.WriteString(renderImports(imports))
	fmt.Fprintf(&b, "func main() {\n\t%s\n}\n", call)

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("formatting generated source: %w", err)
	}
	return string(formatted), nil
}

// renderImports renders a sorted import block for the given path→package-name
// map, aliasing only when the package name differs from the path's last element.
func renderImports(imports map[string]string) string {
	paths := make([]string, 0, len(imports))
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("import (\n")
	for _, p := range paths {
		if name := imports[p]; name != path.Base(p) {
			fmt.Fprintf(&b, "\t%s %q\n", name, p)
		} else {
			fmt.Fprintf(&b, "\t%q\n", p)
		}
	}
	b.WriteString(")\n\n")
	return b.String()
}

// pkgSelectorRe matches package-qualified identifiers ("pkg.") in a Go literal.
// Struct field names are followed by ':' not '.', so this captures only package
// selectors (and, in composite literals, element type names).
var pkgSelectorRe = regexp.MustCompile(`([a-zA-Z_][a-zA-Z0-9_]*)\.`)

// configImports returns the imports the %#v-rendered config literal references,
// as an import-path→package-name map. It intersects the package selectors that
// actually appear in the literal with the set of packages reachable from the
// config's type, so it imports exactly what the literal qualifies — no unused
// imports for named scalar fields (which %#v prints bare) and no false matches
// from string contents.
func configImports(cfg any, lit string) map[string]string {
	known := map[string]string{} // package name -> import path
	walkPkgPaths(reflect.TypeOf(cfg), known)

	imports := map[string]string{}
	for _, m := range pkgSelectorRe.FindAllStringSubmatch(lit, -1) {
		if p, ok := known[m[1]]; ok {
			imports[p] = m[1]
		}
	}
	return imports
}

// walkPkgPaths records the package name and import path of every named,
// package-scoped type reachable from t (through pointers, slices, arrays, maps
// and struct fields), using the package name reflect reports (the one %#v emits).
func walkPkgPaths(t reflect.Type, known map[string]string) {
	walkPkgPathsSeen(t, known, make(map[reflect.Type]bool))
}

func walkPkgPathsSeen(t reflect.Type, known map[string]string, seen map[reflect.Type]bool) {
	if t == nil {
		return
	}
	if seen[t] {
		return
	}
	seen[t] = true
	if t.PkgPath() != "" && t.Name() != "" {
		s := t.String() // "pkg.Name"
		if i := strings.LastIndex(s, "."); i >= 0 {
			known[s[:i]] = t.PkgPath()
		}
	}
	switch t.Kind() {
	case reflect.Ptr, reflect.Slice, reflect.Array:
		walkPkgPathsSeen(t.Elem(), known, seen)
	case reflect.Map:
		walkPkgPathsSeen(t.Key(), known, seen)
		walkPkgPathsSeen(t.Elem(), known, seen)
	case reflect.Struct:
		for i := 0; i < t.NumField(); i++ {
			walkPkgPathsSeen(t.Field(i).Type, known, seen)
		}
	}
}
