package cli

import (
	"bytes"
	"errors"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"path"
	"strings"
	"testing"

	"github.com/burgrp/bleriot/lib/shared/config"
	"github.com/burgrp/bleriot/lib/shared/inventory"
)

func TestResolveInstance(t *testing.T) {
	one := sampleInstance()
	two := sampleInstance()
	two.Name = "other"
	two.Address = [config.AddrLen]byte{0x99}

	t.Run("sole instance is the default", func(t *testing.T) {
		got, err := resolveInstance(inventory.Inventory{one}, "")
		if err != nil {
			t.Fatalf("resolveInstance: %v", err)
		}
		if got.Name != one.Name {
			t.Fatalf("got %q, want %q", got.Name, one.Name)
		}
	})

	t.Run("named instance", func(t *testing.T) {
		got, err := resolveInstance(inventory.Inventory{one, two}, "other")
		if err != nil {
			t.Fatalf("resolveInstance: %v", err)
		}
		if got.Name != "other" {
			t.Fatalf("got %q, want other", got.Name)
		}
	})

	t.Run("unknown name errors", func(t *testing.T) {
		if _, err := resolveInstance(inventory.Inventory{one}, "nope"); err == nil {
			t.Fatal("expected error for unknown name")
		}
	})

	t.Run("empty inventory errors", func(t *testing.T) {
		if _, err := resolveInstance(inventory.Inventory{}, ""); err == nil {
			t.Fatal("expected error for empty inventory")
		}
	})

	t.Run("ambiguous default errors", func(t *testing.T) {
		if _, err := resolveInstance(inventory.Inventory{one, two}, ""); err == nil {
			t.Fatal("expected error for ambiguous default")
		}
	})
}

func TestRunGenOutput(t *testing.T) {
	inst := sampleInstance() // Config: bobConfig{DefaultRedPeriod:500, DefaultGreenPeriod:100}
	var buf bytes.Buffer
	if err := runGen(inventory.Inventory{inst}, "", &buf); err != nil {
		t.Fatalf("runGen: %v", err)
	}
	out := buf.String()

	// It is valid, parseable Go.
	if _, err := parser.ParseFile(token.NewFileSet(), "main_gen.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}

	wants := []string{
		"//go:build tinygo",
		`// Code generated by "bleriot gen"; DO NOT EDIT.`,
		"package main",
		`"github.com/burgrp/bleriot/lib/node"`,
		"func main() {",
		"bleriotMain(",
		"node.Provisioning{",
		byteArrayLiteral(inst.Address[:]), // RF address
		byteArrayLiteral(inst.Key[:]),     // XTEA key
		"Channel:      37",                // channel number
		"SpreadFactor: 1",                 // SpreadFactorS2
		"DefaultRedPeriod",                // config field baked in
	}
	for _, w := range wants {
		if !strings.Contains(out, w) {
			t.Errorf("generated source missing %q:\n%s", w, out)
		}
	}
}

// bobLikeConfig mirrors a real device config: a flat struct of scalars. Because
// its package is this test package, %#v qualifies it as "cli.bobLikeConfig",
// exercising the import-collection path.
type bobLikeConfig struct {
	Period uint32
}

type recursiveConfig struct {
	Next *recursiveConfig
}

type mutualConfigA struct {
	B *mutualConfigB
}

type mutualConfigB struct {
	A *mutualConfigA
}

func TestRenderProvisioningRecursiveConfig(t *testing.T) {
	inst := sampleInstance()
	inst.Config = &recursiveConfig{}

	out, err := renderProvisioning(inst)
	if err != nil {
		t.Fatalf("renderProvisioning: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main_gen.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
}

func TestRenderProvisioningMutuallyRecursiveConfig(t *testing.T) {
	inst := sampleInstance()
	inst.Config = &mutualConfigA{}

	out, err := renderProvisioning(inst)
	if err != nil {
		t.Fatalf("renderProvisioning: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main_gen.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
}

func TestRunGenImportsNestedSliceMapPackage(t *testing.T) {
	inst := sampleInstance()
	inst.Config = map[string][]config.SpreadFactor{"factors": {config.SpreadFactorS2}}

	var buf bytes.Buffer
	if err := runGen(inventory.Inventory{inst}, "", &buf); err != nil {
		t.Fatalf("runGen: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, `"github.com/burgrp/bleriot/lib/shared/config"`) {
		t.Fatalf("generated source missing nested element package import:\n%s", out)
	}
	if !strings.Contains(out, "[]config.SpreadFactor") {
		t.Fatalf("generated source missing nested typed slice:\n%s", out)
	}
}

func TestGeneratedSourceTypeChecks(t *testing.T) {
	inst := sampleInstance()
	inst.Config = []config.SpreadFactor{config.SpreadFactorS2}
	out, err := renderProvisioning(inst)
	if err != nil {
		t.Fatalf("renderProvisioning: %v", err)
	}
	out += "\nfunc bleriotMain(node.Provisioning, []config.SpreadFactor) {}\n"
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "main_gen.go", out, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
	if _, err := (&types.Config{Importer: generatedSourceImporter{}}).Check("generated", fset, []*ast.File{file}, nil); err != nil {
		t.Fatalf("generated source does not type-check: %v\n%s", err, out)
	}
}

type generatedSourceImporter struct{}

func (generatedSourceImporter) Import(importPath string) (*types.Package, error) {
	pkg := types.NewPackage(importPath, path.Base(importPath))
	switch importPath {
	case firmwareNodePkg:
		fields := []*types.Var{
			types.NewField(token.NoPos, pkg, "Address", types.NewArray(types.Typ[types.Byte], config.AddrLen), false),
			types.NewField(token.NoPos, pkg, "Key", types.NewArray(types.Typ[types.Byte], config.KeyLen), false),
			types.NewField(token.NoPos, pkg, "Channel", types.Typ[types.Uint8], false),
			types.NewField(token.NoPos, pkg, "SpreadFactor", types.Typ[types.Uint8], false),
		}
		name := types.NewTypeName(token.NoPos, pkg, "Provisioning", nil)
		types.NewNamed(name, types.NewStruct(fields, nil), nil)
		pkg.Scope().Insert(name)
	case "github.com/burgrp/bleriot/lib/shared/config":
		name := types.NewTypeName(token.NoPos, pkg, "SpreadFactor", nil)
		types.NewNamed(name, types.Typ[types.Uint8], nil)
		pkg.Scope().Insert(name)
	default:
		return nil, errors.New("unexpected generated source import")
	}
	pkg.MarkComplete()
	return pkg, nil
}

type errorWriter struct{ err error }

func (writer errorWriter) Write([]byte) (int, error) { return 0, writer.err }

func TestRunGenReturnsWriterError(t *testing.T) {
	want := errors.New("writer failed")
	if err := runGen(inventory.Inventory{sampleInstance()}, "", errorWriter{err: want}); !errors.Is(err, want) {
		t.Fatalf("runGen error = %v, want %v", err, want)
	}
}

func TestRunGenImportsConfigPackage(t *testing.T) {
	inst := sampleInstance()
	inst.Config = bobLikeConfig{Period: 7}

	var buf bytes.Buffer
	if err := runGen(inventory.Inventory{inst}, "", &buf); err != nil {
		t.Fatalf("runGen: %v", err)
	}
	out := buf.String()

	if !strings.Contains(out, `"github.com/burgrp/bleriot/lib/site/cli"`) {
		t.Errorf("generated source missing config package import:\n%s", out)
	}
	if !strings.Contains(out, "cli.bobLikeConfig{") {
		t.Errorf("generated source missing config literal:\n%s", out)
	}
}

// TestRunGenNilConfig checks a nil config yields a bleriotMain call with only the
// provisioning argument and no spurious config import.
func TestRunGenNilConfig(t *testing.T) {
	inst := sampleInstance()
	inst.Config = nil

	var buf bytes.Buffer
	if err := runGen(inventory.Inventory{inst}, "", &buf); err != nil {
		t.Fatalf("runGen: %v", err)
	}
	out := buf.String()
	if _, err := parser.ParseFile(token.NewFileSet(), "main_gen.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
	if !strings.Contains(out, "bleriotMain(node.Provisioning{") {
		t.Errorf("expected single-argument bleriotMain call:\n%s", out)
	}
}
