package cli

import (
	"bytes"
	"go/parser"
	"go/token"
	"hash/crc32"
	"strings"
	"testing"

	"github.com/burgrp/bleriot/lib/shared/config"
	"github.com/burgrp/bleriot/lib/shared/inventory"
)

// expectedAddrLiteral renders the byte-array literal the generator must emit for
// a UID's derived address (CRC32, big-endian), matching byteArrayLiteral.
func expectedAddrLiteral(uid [config.UIDLen]byte) string {
	crc := crc32.ChecksumIEEE(uid[:])
	addr := []byte{byte(crc >> 24), byte(crc >> 16), byte(crc >> 8), byte(crc)}
	return byteArrayLiteral(addr)
}

func TestResolveInstance(t *testing.T) {
	one := sampleInstance()
	two := sampleInstance()
	two.Name = "other"
	two.UID = [config.UIDLen]byte{0x99}

	t.Run("sole instance is the default", func(t *testing.T) {
		got, err := resolveInstance(inventory.Inventory{one}, "")
		if err != nil {
			t.Fatalf("resolveInstance: %v", err)
		}
		if got.Name != one.Name {
			t.Fatalf("got %q, want %q", got.Name, one.Name)
		}
	})

	t.Run("named instance", func(t *testing.T) {
		got, err := resolveInstance(inventory.Inventory{one, two}, "other")
		if err != nil {
			t.Fatalf("resolveInstance: %v", err)
		}
		if got.Name != "other" {
			t.Fatalf("got %q, want other", got.Name)
		}
	})

	t.Run("unknown name errors", func(t *testing.T) {
		if _, err := resolveInstance(inventory.Inventory{one}, "nope"); err == nil {
			t.Fatal("expected error for unknown name")
		}
	})

	t.Run("empty inventory errors", func(t *testing.T) {
		if _, err := resolveInstance(inventory.Inventory{}, ""); err == nil {
			t.Fatal("expected error for empty inventory")
		}
	})

	t.Run("ambiguous default errors", func(t *testing.T) {
		if _, err := resolveInstance(inventory.Inventory{one, two}, ""); err == nil {
			t.Fatal("expected error for ambiguous default")
		}
	})
}

func TestRunGenOutput(t *testing.T) {
	inst := sampleInstance() // Config: bobConfig{DefaultRedPeriod:500, DefaultGreenPeriod:100}
	var buf bytes.Buffer
	if err := runGen(inventory.Inventory{inst}, "", &buf); err != nil {
		t.Fatalf("runGen: %v", err)
	}
	out := buf.String()

	// It is valid, parseable Go.
	if _, err := parser.ParseFile(token.NewFileSet(), "provisioning_gen.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}

	wants := []string{
		"//go:build tinygo",
		`// Code generated by "bleriot gen"; DO NOT EDIT.`,
		"package main",
		`"github.com/burgrp/bleriot/lib/node"`,
		"func main() {",
		"bleriotMain(",
		"node.Provisioning{",
		expectedAddrLiteral(inst.UID), // derived RF address
		byteArrayLiteral(inst.Key[:]), // XTEA key
		"Channel:      37",            // channel number
		"SpreadFactor: 1",             // SpreadFactorS2
		"DefaultRedPeriod",            // config field baked in
	}
	for _, w := range wants {
		if !strings.Contains(out, w) {
			t.Errorf("generated source missing %q:\n%s", w, out)
		}
	}
}

// bobLikeConfig mirrors a real device config: a flat struct of scalars. Because
// its package is this test package, %#v qualifies it as "cli.bobLikeConfig",
// exercising the import-collection path.
type bobLikeConfig struct {
	Period uint32
}

func TestRunGenImportsConfigPackage(t *testing.T) {
	inst := sampleInstance()
	inst.Config = bobLikeConfig{Period: 7}

	var buf bytes.Buffer
	if err := runGen(inventory.Inventory{inst}, "", &buf); err != nil {
		t.Fatalf("runGen: %v", err)
	}
	out := buf.String()

	if !strings.Contains(out, `"github.com/burgrp/bleriot/lib/site/cli"`) {
		t.Errorf("generated source missing config package import:\n%s", out)
	}
	if !strings.Contains(out, "cli.bobLikeConfig{") {
		t.Errorf("generated source missing config literal:\n%s", out)
	}
}

// TestRunGenNilConfig checks a nil config yields a bleriotMain call with only the
// provisioning argument and no spurious config import.
func TestRunGenNilConfig(t *testing.T) {
	inst := sampleInstance()
	inst.Config = nil

	var buf bytes.Buffer
	if err := runGen(inventory.Inventory{inst}, "", &buf); err != nil {
		t.Fatalf("runGen: %v", err)
	}
	out := buf.String()
	if _, err := parser.ParseFile(token.NewFileSet(), "provisioning_gen.go", out, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
	if !strings.Contains(out, "bleriotMain(node.Provisioning{") {
		t.Errorf("expected single-argument bleriotMain call:\n%s", out)
	}
}
