// Code generated by bleriot generator for node "heating-controller". DO NOT EDIT.
package main

// DescriptorID identifies this node's register set (§11.6).
const DescriptorID uint32 = 0x1922FAAE

// Wire register IDs (§11.6). Identifier derived from the qualified name.
const (
	RegHeatingState      uint16 = 0x8E22 // heating.state
	RegLedState          uint16 = 0xDE91 // led.state
	RegSensorHumidity    uint16 = 0x158A // sensor.humidity
	RegSensorTemperature uint16 = 0x2E8B // sensor.temperature
)

// RegisterIDs lists every wire register ID on this node.
var RegisterIDs = []uint16{
	RegHeatingState,
	RegLedState,
	RegSensorHumidity,
	RegSensorTemperature,
}
