// Package codegen turns a resolved BleRiot node descriptor into the two
// generated artifacts described in the protocol spec §11.7:
//
//   - Node code: a Go source file compiled into firmware, containing const wire
//     IDs, a slice of all IDs, and the descriptor ID. No per-class
//     wrappers or interfaces are emitted; the firmware backs registers
//     generically by uint16 ID.
//   - Node descriptor: a JSON data file consumed by the hub, which bridges every
//     BleRiot register to the external Registry service generically.
package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"strings"
	"unicode"

	"cli/pkg/descriptor"
)

// NodeCodeOptions controls node-code generation.
type NodeCodeOptions struct {
	// Package is the Go package name for the generated file (e.g. "main").
	Package string
}

// GenerateNodeCode renders the firmware-side Go source for a resolved node.
// The output is gofmt-formatted. It contains only const wire IDs, a RegisterIDs
// slice, and the descriptor ID const — no class-specific types (§11.7).
func GenerateNodeCode(res descriptor.Resolved, opts NodeCodeOptions) ([]byte, error) {
	pkg := opts.Package
	if pkg == "" {
		pkg = "main"
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by bleriot generator for node %q. DO NOT EDIT.\n", res.Node)
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	// Descriptor ID const for firmware/descriptor mismatch detection (§11.6 step 5).
	fmt.Fprintf(&b, "// DescriptorID identifies this node's register set (§11.6).\n")
	fmt.Fprintf(&b, "const DescriptorID uint32 = 0x%08X\n\n", res.Version)

	// Per-register wire ID consts. Already in canonical (sorted) order.
	fmt.Fprintf(&b, "// Wire register IDs (§11.6). Identifier derived from the qualified name.\n")
	fmt.Fprintf(&b, "const (\n")
	idents := make(map[string]string, len(res.Registers))
	used := make(map[string]bool, len(res.Registers))
	for _, r := range res.Registers {
		ident := uniqueIdent("Reg"+exportIdent(r.Name), used)
		idents[r.Name] = ident
		fmt.Fprintf(&b, "\t%s uint16 = 0x%04X // %s\n", ident, r.ID, r.Name)
	}
	fmt.Fprintf(&b, ")\n\n")

	// Slice of all IDs for iteration / table setup.
	fmt.Fprintf(&b, "// RegisterIDs lists every wire register ID on this node.\n")
	fmt.Fprintf(&b, "var RegisterIDs = []uint16{\n")
	for _, r := range res.Registers {
		fmt.Fprintf(&b, "\t%s,\n", idents[r.Name])
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated node code: %w", err)
	}
	return src, nil
}

// jsonRegister is the on-disk shape of one register in the node descriptor.
type jsonRegister struct {
	ID         uint16            `json:"id"`
	Name       string            `json:"name"`
	Class      string            `json:"class"`
	Instance   string            `json:"instance"`
	Type       string            `json:"type"`
	Multiplier int32             `json:"multiplier"`
	Divider    int32             `json:"divider"`
	Metadata   map[string]string `json:"metadata"`
}

// jsonDescriptor is the on-disk shape of the node descriptor (§11.7). It carries
// no node name and no RF channel: a node's name comes from its per-device
// instance file on the hub, and its channel is provisioned per device (§11.5).
// The descriptor is a shared, per-type artifact. Its descriptor ID is not stored
// in the file; the file is content-addressed by that ID (the file name).
type jsonDescriptor struct {
	Metadata  map[string]string `json:"metadata"`
	Registers []jsonRegister    `json:"registers"`
}

// GenerateDescriptorJSON renders the hub-side JSON node descriptor for a
// resolved node (§11.7). Registers appear in canonical order.
func GenerateDescriptorJSON(res descriptor.Resolved) ([]byte, error) {
	jd := jsonDescriptor{
		Metadata:  emptyIfNil(res.Metadata),
		Registers: make([]jsonRegister, 0, len(res.Registers)),
	}
	for _, r := range res.Registers {
		jd.Registers = append(jd.Registers, jsonRegister{
			ID:         r.ID,
			Name:       r.Name,
			Class:      r.Class,
			Instance:   r.Instance,
			Type:       string(r.Type),
			Multiplier: r.Multiplier,
			Divider:    r.Divider,
			Metadata:   emptyIfNil(r.Metadata),
		})
	}

	out, err := json.MarshalIndent(jd, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal node descriptor: %w", err)
	}
	return append(out, '\n'), nil
}

// emptyIfNil returns a non-nil map so JSON renders {} rather than null.
func emptyIfNil(m map[string]string) map[string]string {
	if m == nil {
		return map[string]string{}
	}
	return m
}

// exportIdent converts a qualified register name like "outdoor.temperature"
// into an exported Go identifier fragment like "OutdoorTemperature".
func exportIdent(qualified string) string {
	var sb strings.Builder
	upNext := true
	for _, r := range qualified {
		switch {
		case r == '.' || r == '_' || r == '-' || unicode.IsSpace(r):
			upNext = true
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			if upNext {
				sb.WriteRune(unicode.ToUpper(r))
				upNext = false
			} else {
				sb.WriteRune(r)
			}
		}
	}
	id := sb.String()
	if id == "" || unicode.IsDigit(rune(id[0])) {
		id = "X" + id
	}
	return id
}

// uniqueIdent disambiguates identifiers that collide after sanitization by
// appending a numeric suffix. Deterministic given canonical input order.
func uniqueIdent(base string, used map[string]bool) string {
	if !used[base] {
		used[base] = true
		return base
	}
	for i := 2; ; i++ {
		cand := fmt.Sprintf("%s%d", base, i)
		if !used[cand] {
			used[cand] = true
			return cand
		}
	}
}
